### ISSUE TITLE
cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer'

### ISSUE THREAD

**Issue by fang196** [atonderski/lidarclip#3]
I encountered this problem when running `python scripts/cache_embeddings.py`.
Instead of using docker, I used conda environment:
torch                     1.9.0a0+gitd69c22d           dev_0    <develop>
pytorch-lightning         1.6.2                    pypi_0    pypi
mmcv-full                 1.3.8                    pypi_0    pypi
mmdet                     2.14.0                   pypi_0    pypi
mmsegmentation            0.14.1                   pypi_0    pypi
transformers              4.33.2                   pypi_0    pypi

Below is the detailed error massage:
/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py:27: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/utils/transformer.py:21: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
 warnings.warn(
Traceback (most recent call last):
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/utils/transformer.py", line 18, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/miniconda3/envs/lidarclip/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/cache_embeddings.py", line 13, in <module>
    from lidarclip.model.sst import LidarEncoderSST
  File "/lidarclip/lidarclip/model/sst.py", line 5, in <module>
    from mmdet3d.models import build_model
  File "/lidarclip/SST/mmdet3d/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/lidarclip/SST/mmdet3d/models/backbones/__init__.py", line 1, in <module>
    from mmdet.models.backbones import SSDVGG, HRNet, ResNet, ResNetV1d, ResNeXt
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .detectors_resnet import DetectoRS_ResNet
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/backbones/detectors_resnet.py", line 10, in <module>
    from .resnet import BasicBlock
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 10, in <module>
    from ..utils import ResLayer
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/utils/__init__.py", line 10, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/utils/transformer.py", line 24, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py)

**Comment by fang196** [comment]
I have solved this problem.

For `ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory`, I rebuild pytorch.

For `cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer'`, I comment `from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention` in `/miniconda3/envs/lidarclip/lib/python3.8/site-packages/mmdet/models/utils/transformer.py` line 24.
